name: cencus_env
channels:
  - defaults
  - conda-forge

dependencies:
  - scikit-learn=1.2.2
  - pandas
  - ipywidgets
  - pyarrow=10.0.1
  - seaborn=0.12.2
  - pytest=7.3.1
  - jupyterlab=3.6.3
  - fastapi
  - uvicorn=0.22.0
  - git=2.40.1
  - xgboost=1.7.4
  - bayesian-optimization=1.4.3
  - shap=0.41.0
  - httpx
  - flake8=6.0.0